name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build and upload Rust binary to GitHub Releases
      uses: taiki-e/upload-rust-binary-action@v1.12.0
      with:
        # Comma-separated list of binary names (non-extension portion of filename) to build and upload. Note that glob pattern is not supported yet.
        bin: discord-notifier
        # Target name, default is host triple
        # target: # optional
