name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Rust Release Windows binary
      uses: rust-build/rust-build.action@v1.4.3
      with:
        # Output target
        RUSTTARGET: x86_64-pc-windows-gnu
    - name: Rust Release Linux binary
      uses: rust-build/rust-build.action@v1.4.3
      with:
        # Output target
        RUSTTARGET: x86_64-unknown-linux-musl


